# Generated by Django 2.2.2 on 2019-08-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EyeCandy_Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='to_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
